services:
  php83:
    container_name: curl-wrap
    build: ./docker
    working_dir: /app
    volumes:
      - ./:/app
    # Run a script or just show the PHP version
    command: bash -c "composer install"
